runtime: nodejs22
instance_class: F2

env_variables:
  DB_USER: dav
  DB_PASS: 
  DB_NAME: mysql
  DB_PORT: 3306
  INSTANCE_HOST: 10.63.16.2
  PRIVATE_IP: TRUE

vpc_access_connector:
  name: projects/infra-pattug/locations/europe-west6/connectors/app-engine-to-sql
